language:
  - cpp

os: 
 - linux

compiler: 
 - gcc
 - clang

addons:
  apt:
    packages:
      - clang
      - gcc
      - libirrlicht-dev
      - libbullet-dev
      - libfreetype6-dev

script:
  - make
