language:
  - cpp
  
sudo: required
dist: trusty
  
compiler: 
 - gcc
 - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - gcc-5
      - g++-5
      - libirrlicht-dev
      - libbullet-dev
      - libfreetype6-dev
	  - cmake
before_script:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5

script:
  - mkdir buid
  - cd build
  - cmake .. -DDEBUG=1
  - make
