language: cpp
os: 
 - linux
compiler: 
 - gcc
install: apt-get install irrlicht-devel bullet-devel freetype-devel
script:
  - mkdir build
  - cd build
  - cmake .. && make
env:
  global:
- LANG="en_US.UTF-8"
